name: Weather Bot

on:
  schedule:
    - cron: "*/5 * * * *"   # testing every 5 minutes
  workflow_dispatch:

jobs:
  run-weather-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          API_KEY: ${{ secrets.API_KEY }}
          FROM_NUM: ${{ secrets.FROM_NUM }}
          TO_NUM: ${{ secrets.TO_NUM }}
        run: python rain.py
